set(_CATKIN_CURRENT_PACKAGE "Inverse_Kinematics")
set(Inverse_Kinematics_VERSION "0.0.0")
set(Inverse_Kinematics_MAINTAINER "emre <emre@todo.todo>")
set(Inverse_Kinematics_PACKAGE_FORMAT "2")
set(Inverse_Kinematics_BUILD_DEPENDS "sensor_msgs" "std_msgs" "geometry_msgs")
set(Inverse_Kinematics_BUILD_EXPORT_DEPENDS "sensor_msgs" "std_msgs" "geometry_msgs")
set(Inverse_Kinematics_BUILDTOOL_DEPENDS "catkin")
set(Inverse_Kinematics_BUILDTOOL_EXPORT_DEPENDS )
set(Inverse_Kinematics_EXEC_DEPENDS "sensor_msgs" "std_msgs" "geometry_msgs")
set(Inverse_Kinematics_RUN_DEPENDS "sensor_msgs" "std_msgs" "geometry_msgs")
set(Inverse_Kinematics_TEST_DEPENDS )
set(Inverse_Kinematics_DOC_DEPENDS )
set(Inverse_Kinematics_URL_WEBSITE "")
set(Inverse_Kinematics_URL_BUGTRACKER "")
set(Inverse_Kinematics_URL_REPOSITORY "")
set(Inverse_Kinematics_DEPRECATED "")